import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { WishlistProvider } from 'providers/WishlistProvider';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Tech Enablers store ecommerce app',
  description: 'Generated by Medusa and NextJS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <main>
          <WishlistProvider>{children}</WishlistProvider>
        </main>
      </body>
    </html>
  );
}
